import type { Metadata } from "next";
import "./globals.scss";
import { Header } from "~/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="tokyonight-storm">
      <body className={`antialiased`}>
        <Header />

        {children}
      </body>
    </html>
  );
}
